### ISSUE TITLE
The Tracking Screen is Broken/Scaled/Enlarged [Linux]

### ISSUE THREAD

**Issue by ShivaPrakash-006** [kodjodevf/mangayomi#186]
### Steps to reproduce

1. Open Mangayomi
2. Open any Anime/Manga
3. Click Tracking

### Expected behavior

It should open a reasonably sized window.

### Actual behavior

It an enlarged window with weird click boxes.
![image_2024-05-18_171351861](https://github.com/kodjodevf/mangayomi/assets/87466383/c1ab37bb-d223-4655-a288-5cd4b9aeb6f1)

### Mangayomi version

0.2.45

### Device

Dell Latitude E6430s - Garuda Linux - GNOME 46.1

### Other details

Linux - Garuda Linux with GNOME 46.1. Installed through AppImage

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.
