### ISSUE TITLE
Changing an anime’s tracking progress on IOS incorrectly changes status of show (Anilist)

### ISSUE THREAD

**Issue by tyrohellion** [kodjodevf/mangayomi#58]
### Steps to reproduce

Enable tracking for any anime and change the progress from any number to something else. Then close out of the menu and reopen it

### Expected behavior

When I change a shows progress from 1 to 2 it should change no other values

### Actual behavior

Instead if I changed a shows progress from 1 to 2 it changes the shows status from “Watching” to “Rewatching” and I have to change it back every time

### Mangayomi version

0.1.0

### Device

iPhone 13 Pro

### Other details

This is with anilist, I haven’t tried to see if the bug persists with other trackers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.
